export default {
  AUTH_EXTERNAL_PROVIDER: 'AUTH_EXTERNAL_PROVIDER',
  AUTHORIZATION_DATA: 'AUTHORIZATION_DATA',
  NEW_ACCOUNT: 'NEW_ACCOUNT',
  ADD_NEW_ACCOUNT_REQUESTED: 'ADD_NEW_ACCOUNT_REQUESTED',
  ADD_NEW_ACCOUNT_SUCCEEDED: 'ADD_NEW_ACCOUNT_SUCCEEDED',
  ADD_NEW_ACCOUNT_FAILED: 'ADD_NEW_ACCOUNT_FAILED',
  REQUEST_STARTED: 'REQUEST_STARTED',
  REQUEST_FINISHED: 'REQUEST_FINISHED',
  REQUEST_ERROR: 'REQUEST_ERROR',
  ACCOUNTS_REQUESTED: 'ACCOUNTS_REQUESTED',
  ACCOUNTS_LOADED: 'ACCOUNTS_LOADED',
  SHOW_TOASTR: 'SHOW_TOASTR',
  ADD_NEW_TAG_REQUESTED: 'ADD_NEW_TAG_REQUESTED',
  ADD_NEW_TAG_SUCCEEDED: 'ADD_NEW_TAG_SUCCEEDED',
  ADD_NEW_TAG_TASK_REQUESTED: 'ADD_NEW_TAG_TASK_REQUESTED',
  SIGN_IN_REQUESTED: 'SIGN_IN_REQUESTED',
  SIGN_UP_REQUESTED: 'SIGN_UP_REQUESTED',
  SIGN_IN_EXTERNAL_REQUESTED: 'SIGN_IN_REQUESTED',
  SIGN_UP_EXTERNAL_REQUESTED: 'SIGN_UP_REQUESTED'
}
;
