version: 1.2.5.{build}
os: Visual Studio 2017
platform: Any CPU
configuration: Release

branches:
  only:
    - develop
    - master
skip_commits:
  message: /skip ci/      # Regex for matching commit message

skip_tags: true

build:
  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages
  include_nuget_references: false  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  
build_script:
  - ps: nuget sources add -Name MyGetXunit -Source https://www.myget.org/F/xunit/api/v3/index.json
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: dotnet build

environment:
  instaapiuserpassword:
    secure: 7eAl+O5i5BxXWexd26z+wg==

test: off
